---
- hosts: all
  tasks:
  - name: Set default user
    become: true
    user:
      name: "{{ user }}"
      comment: "{{ user }}"
      state: "{{ state }}"
      group: "{{ group }}"
      shell: "{{ shell }}"
      update_password: always
      password: "{{ password | password_hash('sha512') }}"
