---
- hosts: all
  tasks:
  - name: Set default user
    become: true
    user:
      name: "{{ user }}"
      comment: "{{ user }}"
      state: present
      group: sudo
      shell: /bin/bash
	    update_password: always
