---
- hosts: all
  remote_user: "{{ user }}"
  tasks:
  - name: Set default user
    become: true
    user:
      name: "{{ manage_user }}"
      comment: "{{ manage_user }}"
      state: "{{ state }}"
#      groups: "{{ group }}"
      shell: "{{ shell }}"
      update_password: always
      password: "{{ password | password_hash('sha512') }}"
