---
- hosts: all
  remote_user: "{{ user }}"
  tasks:
  - name: Set authorized key took from file
    become: true
    authorized_key:
      user: "{{ manage_user }}"
      state: present
      key: "{{ lookup('file', '{{ pubkey }}') }}"
