---
- hosts: all
  tasks:
  - name: Set default user
    become: true
    user:
      name: "{{ user }}"
      comment: "{{ user }}"
      state: present
      group: admin
      shell: /bin/bash
      update_password: always
      password: "{{ password | password_hash('sha512') }}"
