---
- hosts: all
  remote_user: <user to login as>
  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: [[ user ]]
      state: present
      key: "{{ lookup('file', '{{ pubkey }}') }}"
